services:
  database:
    container_name: meraki-database
    restart: unless-stopped
    image: postgres:latest
    env_file:
      - .env      
    ports:
      - "5432:5432"
    volumes:
      - ./database/db_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - reverse-proxy
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

  bucket:
    image: nginx:alpine
    container_name: meraki-bucket
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./filestorage/bucket:/usr/share/nginx/html:ro
    networks:
      - reverse-proxy

  backend:
    container_name: meraki-backend
    build:
      context: ./backend
      dockerfile: Dockerfile 
    env_file:
      - .env
    ports:
      - "3000:3000"
    command: sh -c "npm run build && node dist/index.js"
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
      bucket:
        condition: service_started
    networks:
      - reverse-proxy
  
  frontend:
    container_name: meraki-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "5173:5173"
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_started
    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    external: true