services:
  database:
    container_name: meraki-database
    restart: unless-stopped
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./database/db_data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d/:ro
    networks:
      - localdev-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    container_name: meraki-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    command: sh -c "npm run dev"
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
    networks:
      - localdev-network

networks:
  localdev-network:
    driver: bridge
