services:
  database:
    container_name: meraki-database
    restart: unless-stopped
    image: postgres:latest
    env_file:
      - .env      
    ports:
      - "5432:5432"
    volumes:
      - ./database/db_data:/var/lib/postgresql/data
    networks:
      - reverse-proxy

  bucket:
    image: nginx:alpine
    container_name: meraki-bucket
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./bucket:/usr/share/nginx/html:ro
    networks:
      - reverse-proxy

  backend:
    container_name: meraki-backend
    build:
      context: ./backend
      dockerfile: Dockerfile 
    env_file:
      - .env
    ports:
      - "3000:3000"
    command: sh -c "npm run build && node dist/index.js"
    restart: unless-stopped
    networks:
      - reverse-proxy
  
  frontend:
    container_name: meraki-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
    ports:
      - "5173:5173"
    restart: unless-stopped
    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    external: true